### ISSUE TITLE
🎨 Split the entity-interfaces into serializable and non-serializable parts

### ISSUE THREAD

**Issue by heikomat** [process-engine/process_engine_contracts#12]
#### Describe your issue

We currently have no interfaces that correctly describe the serialized versions of entities one can request via http or messagebus. These Interfaces are needed in the consumer_client

#### How can others reproduce the issue?

The Interfaces used in the consumer_client contain methods that are not actually on the objects they describe. This probably makes intellisense show these methods even though they are not actually there.

#### Possible solution

The entity-interfaces should be split in two: One that only contains the serializable members, and one that extends that and also contains the methods. For example:

```TypeScript
export interface IFlowDef extends IEntityBase {
  name: string;
  key: string;
  processDef: IProcessDefEntity;
  source: INodeDefEntity;
  target: INodeDefEntity;
  condition: string;
}

export interface IFlowDefEntity extends IFlowDef, IEntity {
  getProcessDef(context: ExecutionContext): Promise<IProcessDefEntity>;
  getSource(context: ExecutionContext): Promise<INodeDefEntity>;
  getTarget(context: ExecutionContext): Promise<INodeDefEntity>;
}
```

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
This has become obsolete with the introduction of the refactored object model.
